### ISSUE TITLE
installation fail on suse os

### ISSUE THREAD

**Issue by jaesik817** [cmu-db/ottertune#165]
Hi,

I tried to install this repo. on suse, I got followed error.

I think the reason is python-mysqldb package, which is not supported in suse, thus I installed python-mysql.

could you check this problem?

Thanks.

BRs, Jaesik Yoon.

$python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, djcelery, sessions, sites, website
Running migrations:
  Applying website.0002_enable_compression...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 107, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 128, in _run_sql
    schema_editor.execute(sql, params=params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 201, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1911, "Unknown option 'COMPRESSION'")

**Comment by bohanjason** [comment]
Hi Jaesik, 
It seems that Django fails to compress the table. 
https://github.com/cmu-db/ottertune/blob/1babeeb17e6ae033ddc179c4739fd071f1671821/server/website/website/migrations/0002_enable_compression.py#L21
I agree that the reason is python-mysql connector if you can run the same sql in your MySQL database successfully.
One simple solution is to skip this compression step when loading the database. You can simply change the files in ottertune/server/website/website/migrations/
Besides, we recommend to use Python 3.5+, otherwise you may meet some issues. Details can be found in Wiki. It's kind of messy now, we are still working on the documentation. 

Bohan

**Comment by jaesik817** [comment]
thank you for your kindly response.

With your recommendation, I jumped this issue (skip the compression).

For your later issue tracking,

I tried to install ottertune on SUSE 12.1 and use python-MySQL-python.
https://software.opensuse.org/package/python-MySQL-python

The library didn't support compression.

Just to list-up the issues on your side.

Thanks.

Best Regards, Jaesik.
