### ISSUE TITLE
Ottertune not working when postgresql version is 9.5. KeyError: 'pg_stat_database.xact_commit' And Exception: Cannot find objective function

### ISSUE THREAD

**Issue by KhangxLi** [cmu-db/ottertune#169]
Hi, I've been trying to run fab upload_result with your sample_output/postgres files as well as with my own files. In both cases pg_stat_database.xact_commit is not recognized.

`[20/Jun/2018 17:38:03] INFO [django.request:19] POST /new_result/ - 500
[20/Jun/2018 17:38:03] ERROR [django.server:131] "POST /new_result/ HTTP/1.1" 500 27
[20/Jun/2018 17:41:43] INFO [django.request:12] POST /new_result/
[20/Jun/2018 17:41:43] ERROR [django.request:124] Internal Server Error: /new_result/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ottertune/server/website/website/views.py", line 380, in new_result
    return handle_result_files(session, request.FILES)
  File "/ottertune/server/website/website/views.py", line 436, in handle_result_files
    dbms.pk, metric_dict, observation_time, session.target_objective)
  File "/ottertune/server/website/website/parser/parser.py", line 67, in convert_dbms_metrics
    numeric_metrics, observation_time, target_objective)
  File "/ottertune/server/website/website/parser/base.py", line 183, in convert_dbms_metrics
    metric_data[self.target_metric(target_objective)]
KeyError: 'pg_stat_database.xact_commit'`

**Comment by KhangxLi** [comment]
I found the upload works if I manually and wrongfully change the database_version in summary.json from postgres 9.5 to 9.6 (and do the same on my session to upload to).

**Comment by bohanjason** [comment]
Thanks.  We will look into it. I tuned Postgres 9.3 before. Not sure about other versions. @11hifish may have tested on more Postgres versions.

**Comment by KhangxLi** [comment]
Again: Only for 9.5 (different error for some reason)

Internal Server Error: /new_result/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ottertune/server/website/website/views.py", line 380, in new_result
    return handle_result_files(session, request.FILES)
  File "/ottertune/server/website/website/views.py", line 436, in handle_result_files
    dbms.pk, metric_dict, observation_time, session.target_objective)
  File "/ottertune/server/website/website/parser/parser.py", line 67, in convert_dbms_metrics
    numeric_metrics, observation_time, target_objective)
  File "/ottertune/server/website/website/parser/base.py", line 176, in convert_dbms_metrics
    raise Exception("Cannot find objective function")
Exception: Cannot find objective function
