### ISSUE TITLE
Possible tuner bug

### ISSUE THREAD

**Issue by Rucchao** [cmu-db/ottertune#175]
I use the latest version and data from the data generator, after everything is set, when I upload the data to the tunning session, the asyc_task(line 272) complains an error saying that: 

AttributeError: 'OneHotEncoder' object has no attribute 'n_values_'

I can run the tuner correctly before June 13, would you please fix this error, thanks.

**Comment by swimj** [comment]
Will look into this. Sorry for the bug!

**Comment by swimj** [comment]
Hey @Rucchao , what version so scikit-learn are you using? We are assuming 0.19.*, where OneHotEncoder has an n_values_ attribute (see http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html), so the error you're encountering shouldn't be possible in that API. 

However, in 0.20 I see that they are in the process of deprecating this attribute (see http://scikit-learn.org/dev/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn.preprocessing.OneHotEncoder).  However, that still shouldn't be causing you any error, which is a little weird. Still, can you let me know your version of scikit-learn?

**Comment by Rucchao** [comment]
The _pip show_ its version is 0.19.1, and I installed all the dependencies from the requirement.txt , my python version is 3.5.1. Maybe I could revert to previous the git version to check if it is my problem.

**Comment by swimj** [comment]
Ok good to know. If you just want to use some version of Ottertune now, you can revert to the old version until I fix this. My code, that is triggering your exception, was checked in after June 13.

I actually have a guess as to what is going wrong: if there are no categorical knobs in your generated data, then the DummyEncoder might not be getting initialized, thus n_values_ is not set. I'll try to put in a fix for that in the next couple days.

**Comment by bohanjason** [comment]
Still not work. I tried on Postgres 9.3 and met same errors. @swimj  Could you please help fix it and test it by submitting a tuning task ? Thanks. 

[2018-08-22 18:16:38,153: ERROR/MainProcess] Task configuration_recommendation[9d37d220-b3ed-4ec2-8b30-6f639db8cd20] raised unexpected: AttributeError("'OneHotEncoder' object has no attribute 'n_values_'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/bohan/ottertune/server/website/website/tasks/async_tasks.py", line 383, in configuration_recommendation
    res = model.predict(X_samples, constraint_helper=constraint_helper)
  File "/home/bohan/ottertune/server/analysis/gp_tf.py", line 455, in predict
    xt_valid = constraint_helper.apply_constraints(sess.run(xt_))
  File "/home/bohan/ottertune/server/analysis/constraints.py", line 38, in apply_constraints
    n_values = self.encoder_.n_values_
AttributeError: 'OneHotEncoder' object has no attribute 'n_values_'

**Comment by bohanjason** [comment]
I change ottertune/server/website/website/tasks/async_tasks.py to the previous one ([link](https://github.com/cmu-db/ottertune/blob/362026dd4110eaed57c1867eeecc30a6029226e1/server/website/website/tasks/async_tasks.py)) to avoid calling dummy code functions. Users can do the same thing before the bug is fixed.
