### ISSUE TITLE
Error running LHS (3rd iteration)

### ISSUE THREAD

**Issue by dvanaken** [cmu-db/ottertune#301]
```
[11/Dec/2019 13:26:42] ERROR [celery.worker.job:282] Task aggregate_target_results[5d5ae263-1ed5-4a2f-8e0b-875a507b59f2] raised unexpected: DoesNotExist('Result matching query does not exist.',)

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 240, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 438, in __protected_call__

    return self.run(*args, **kwargs)

  File "/app/website/website/tasks/async_tasks.py", line 161, in aggregate_target_results

    newest_result = Result.objects.get(pk=result_id)

  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 380, in get

    self.model._meta.object_name

website.models.DoesNotExist: Result matching query does not exist.
```

**Comment by dvanaken** [comment]
Resolved. Each Docker web service must have its own rabbitmq service.
